apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    component: api
    app: frontend
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: frontend
  selector:
    app: todo
    component: frontend
  type: LoadBalancer
